site_name: URT Visualisation
site_url: https://pages.github.com/minh-dng/urt-visualisation
repo_url: https://github.com/minh-dng/urt-visualisation
repo_name: minh-dng/urt-visualisation
edit_uri: edit/main/docs/

nav:
  - Home:
      - About: index.md
      - Colour: colour.md
  - Python:
      - Usage: python/usage.ipynb
      - Install: python/install.md
      - API:
          - Plot: python/plot.md
          - Colour: python/colour.md
      - Development:
          - Contribute: python/dev.md
          - Todo: python/todo.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [py]
          import:
            - https://matplotlib.org/stable/objects.inv
          options:
            # show_source: false
            # group_by_category: true
            # show_category_heading: true
            members_order: source
            filters: ["!^_", "^__init__$"]
            merge_init_into_class: true
            line_length: 88
            signature_crossrefs: true
            show_root_toc_entry: false
            # show_root_full_path: false
            # show_symbol_type_toc: true
            # show_if_no_docstring: true
  - search
  - offline
  # - mkdocs_matplotlib
  - mkdocs-jupyter:
      execute: true

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "deep orange"
      accent: "light blue"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "blue grey"
      accent: "lime"
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
